"""Alembic migration script template.

Each migration file is generated from this template.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import table, column

revision = '9ab7a332ef6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmarks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('engine', sa.String(length=100), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('memory_mb', sa.Float(), nullable=True),
    sa.Column('device', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmarks_created_at'), 'benchmarks', ['created_at'], unique=False)
    op.create_index(op.f('ix_benchmarks_engine'), 'benchmarks', ['engine'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('fraud_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inference_log_id', sa.String(length=36), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fraud_probability', sa.Float(), nullable=False),
    sa.Column('is_fraud', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_cases_created_at'), 'fraud_cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_fraud_cases_is_fraud'), 'fraud_cases', ['is_fraud'], unique=False)
    op.create_index(op.f('ix_fraud_cases_risk_level'), 'fraud_cases', ['risk_level'], unique=False)
    op.create_index(op.f('ix_fraud_cases_transaction_id'), 'fraud_cases', ['transaction_id'], unique=True)
    op.create_table('models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_type', sa.String(length=100), nullable=False),
    sa.Column('framework', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('input_schema', sa.Text(), nullable=True),
    sa.Column('output_schema', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('operators_supported', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=False)
    op.create_table('inference_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('api_key_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('input_shape', sa.Text(), nullable=True),
    sa.Column('output_shape', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inference_logs_created_at'), 'inference_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_inference_logs_model_id'), 'inference_logs', ['model_id'], unique=False)
    op.create_index(op.f('ix_inference_logs_status'), 'inference_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inference_logs_status'), table_name='inference_logs')
    op.drop_index(op.f('ix_inference_logs_model_id'), table_name='inference_logs')
    op.drop_index(op.f('ix_inference_logs_created_at'), table_name='inference_logs')
    op.drop_table('inference_logs')
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_fraud_cases_transaction_id'), table_name='fraud_cases')
    op.drop_index(op.f('ix_fraud_cases_risk_level'), table_name='fraud_cases')
    op.drop_index(op.f('ix_fraud_cases_is_fraud'), table_name='fraud_cases')
    op.drop_index(op.f('ix_fraud_cases_created_at'), table_name='fraud_cases')
    op.drop_table('fraud_cases')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_benchmarks_engine'), table_name='benchmarks')
    op.drop_index(op.f('ix_benchmarks_created_at'), table_name='benchmarks')
    op.drop_table('benchmarks')
    # ### end Alembic commands ###
