"""Alembic migration script template.

Each migration file is generated from this template.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import table, column

revision = 'da7b79bcd90d'
down_revision = '9ab7a332ef6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_fraud_cases_reviewed_by'), 'fraud_cases', ['reviewed_by'], unique=False)
    op.create_index('idx_inference_logs_model_id_created_at', 'inference_logs', ['model_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_inference_logs_api_key_id'), 'inference_logs', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_inference_logs_user_id'), 'inference_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_models_created_by'), 'models', ['created_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_models_created_by'), table_name='models')
    op.drop_index(op.f('ix_inference_logs_user_id'), table_name='inference_logs')
    op.drop_index(op.f('ix_inference_logs_api_key_id'), table_name='inference_logs')
    op.drop_index('idx_inference_logs_model_id_created_at', table_name='inference_logs')
    op.drop_index(op.f('ix_fraud_cases_reviewed_by'), table_name='fraud_cases')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    # ### end Alembic commands ###
