/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited manually.
// It is auto-generated by Next.js and committed to git so that
// `tsc --noEmit` works on CI without running `next build` first.
// See https://nextjs.org/docs/app/api-reference/config/typescript
